routes/web.php
<?php
use App\Type;
use App\Recipe;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/recipes/busca', function () {

    //pruebas para mostrar los datos relacionados
    //return Type::find(1)->recipe; 
    return Type::pluck("id","type");
});

//prueba para mostrar el id de un select al seleccionarlo
Route::get('/recipes/pruebas', function () {
    return view("/recipes/pruebas");
    
});

Route::get('/', function() 
{
    /*user=Auth::user();

    if($user->esAdmin())
    {
        echo 'Administrador';
    }
    else
    {
        echo 'Otro';
    };
*/ 
    //para que inicie con la vista de autenticacion
    return view("auth/login");
    
})->name('login');

//como en  las rutas automaticas toma la carpeta inicial recipes, en la ruta
//luego de public va recipes. y las diferentes views
Route::resource('recipes','RecipeController');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

//debe validar si es administrador para entrar al admin
Route::get('/admin','AdministradorController@Index');

//Route::get('/index_ru','UserController@index_ru');

Route::resource('users','UserController');
//Route::POST('/index_ru/destroy','UserController@destroy');




Route::get('/pdf', 'RecipeController@viewpdf');
   
   //$recipes= Recipe::all();
   //$pdf=PDF::LoadView('rep.r1',['recipes'=>$recipes]);
   //return $pdf->download('r1.pdf'); 
//});

/*
esta ruta se declaro para que se pueda invocar la funcion filePDF
duda: porque no pide ruta declarada para la otra funcion creada que
fue viewpdf. dice la ayuda que se requieren rutas para cualquier metodo
que se invoque desde formularios o enlaces
llamado desde un formulario con GET: <form action="{{action('RecipeController@filePDF')}}" method="GET">
*/
Route::GET('/filePDF', 'RecipeController@filePDF');
//Route::get('/filePDF', array('uses' => 'RecipeController@filePDF'));


/* <a href="{{url('recipes.indexdt')}}">Recipes DT</a> 
la duda es que no llama a la view por medio del controller, por lo 
tanto no le pasa los datos para llenar la tabla, y aun asi al abrir
sale la tabla llena
*/

/* llamar directo a la view para el datatable 
en primera instancia se aprecia que no deberia armarse data desde aqui
sino en el controlador

*/
Route::get('/indexdt', function(){
    $myres=Recipe::all();
    return view('recipes.indexdt')->with('myres',$myres);
});

Route::get('/indexcard', function(){
    $recipes=Recipe::orderby('id','desc')->take(3)->get();
    return view('recipes.indexcard')->with('recipes',$recipes);
});

app/User.php
<?php

namespace App;


use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use App\Role;



class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


//se modifico belongsTo por belongsToMany
    //public function role()
    //{
    //    return $this->belongsToMany('App\Role');
    //}

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }


//creada en la practica del video de middleware

    public function esAdmin()
    { 
        
            if(!$this->role->nombre_rol=='administrador')
            {
                return false;
            }
            else
            {
                return true;
            }
   
    }
    
 //valida si vienen uno o varios roles en un array   
    public function hasAnyRole($roles){
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }
        return false;
    }
    
//valida si el usuario tiene relacionado algun ro
    public function hasRole($role){
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        }
        return false;
    }


    public function authorizeRoles($roles){
        if ($this->hasAnyRole($roles)) {
            return true;
        }
        //busca el 401 autom...
        abort(401, '');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;

use Illuminate\Http\Request;
use App\User;
use App\Role;

class UserController extends Controller
{
    public function index(Request $req){

        $req->user()->authorizeRoles(['admin']); //solo autorizado a admin

        /** dadas las definiciones de las relaiones en cada uno de los modelos
         * mostrar datos de relaciones varios a varios se hace con las siguientes
         * instrucciones
         * 
         * 1.- se crea el controlador UserC.., ya que se mostraran cosas referentes
         * a ese modelo
         * 2.- $users = User::with('roles')->get();
         * 3.- en la vista se itera dos veces para accesar a los valores de ambas tablas
         * 
         * @foreach($users as $user)
         * @foreach($user->roles as $role)
         *
         * <tr id="filas">
         * <th scope="row">{{$user->id}}</th>
         * <td >{{$user->name}}</td>
         * <td >{{$role->name}}</td>
         * 
         */

         //sintaxis eloquent
        //$users=User::all();
        //$users = User::with('roles')->get();

        //sintaxis anterior requiere ser explicito con name de user y rol
        $users=DB::select('select users.id,users.name as usname,users.email,
        roles.name as rolname,roles.description
        from users inner join 
        role_user on users.id=role_user.user_id inner join roles 
        on role_user.role_id=roles.id');


        return view('users.index',compact('users'));

    }

    public function create()
    {
        
        
        
    }


    public function destroy(User $user)
    {
        
        $user->delete(); //solo borra en users

        //$user->roles()->delete(); //borra todo roles
        //$user->role_user()->where('user_id',$user->id)->delete(); borra el rol del user actual
        //con role_user no funciona
    
        $user->roles()->detach(); 
        
        /**recordar que se pueden utilizar otros metodos, tales como los trigers desde
         * la base de datos, o los cascade desde la migracion. en este caso veremos el 
         * codigo eloquent
         */
        
        return redirect()->route('users.index');


    }

    public function edit(User $user)
    {
        $roles=Role::select("id","name")->get();
        /**OJO. aqui habia que mandar ademas de roles para la lista, user para el nombre
         * por lo que, al no saber mandarlo con with, lo mande con compact
         */
        return view("users.edit",compact('user'))->with("roles",$roles);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$userid)
    {               
        //no quiero actualizar user, sino role_user. el problema es que se trata de una
        //entidad diferente, deberia tener su propio modelo
        
        //userid trae por post el valor del control del mismo nombre, se ponen dos parametros
        //porque el post no trae user->id, sino el name

        /**LA VENTAJA DE LAS RUTAS ADMINISTRADAS Y LOS CONTROLADORES CON RECUROS 
         * AL ESTAR EN EL AMBITO DE USER, Y AL SELECCIONAR UN USER DETERMINADO, LARAVEL
         * CAMBIA AUTOMATICAMENTE LA INFORMACION DEL MISMO
        */

        User::find($userid)->roles()->sync($request->idrole);

        //multiples
        //$user->roles()->sync([$message->id => ['status' => 1 ],$message2->id => ['status' => 1 ] ]);

        return redirect()->route('users.index');
    }
}

resources/views/users/edit.blade.php
@extends('recipes.template')

@section('content')

<div class="container">

<h3>Edit Recipe</h3>

<!--el post llama a la vista update y le pasa el id de recipe
mas abajo especifica que es con el metodo PUT-->
<form action="{{route('users.update',$user->id)}}" method="POST">
@csrf
@method('PUT')

<style>
#image{
    width:200px;
    height:220px
}
</style>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <strong>Name</strong>
            <input type="text" name="name" value="{{$user->name}}" 
            class="form-control" placeholder="user's name" style='text-transform:uppercase'>
           
            
            <div class="form-group">
            <strong>{!! Form::label("id","New role")!!}</strong>
            </div>

            {!!Form::select('idrole',$roles->pluck('name','id')->all(),
            null,['placeholder'=>'--Select role--','class'=>'form-control'])!!}         
           
            
            <!--cacha error-->
            @if($errors->has('name'))
                <strong class="text-danger">{{$errors->first('name')}}</strong>
            @endif
        </div>
    </div>
    
    <div class="col-md-12 text-center" >
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
    
</div>

</form>

</div>


@endsection

resources/views/users/index.blade.php
@extends('recipes.template')

@section('content')



<h2 class="text-center"></h2>

<div class='container'>


<!--se supone que manda a la vista create, AUNQUE SI EL CREATE DEL CONTROLADOR ESTA VACIO
NO MUESTRA NADA-->

<!--recordar que como esta administradas las rutas, es laravel quien pone 
'recipes + el nombre del metodo' aunque en la realidad no sea asi en la estructura
de carpetas-->

<!--
<a class="btn btn-info mb-2" href="{{route('recipes.create')}}">New recipe</a>
-->
<style type="text/css">
  #tabindex{
    font-size:0.7em;
    
  }
 
  #tabindex #filas{
    padding:0.7em;
    
  }

  #tabindex #encab{
    padding:0.7em;
    
  }
 
  #elim, #edit{
    /*float:right;*/
    padding-top:0px;
    font-size:0.75em;
    
  }

  #elim{
    float:right;
    margin-top:-14px;

    width:38px;
    height:15px;
    font-size:0.73em;
  }

  #edit{
    width:50px;
    height:22px;

  }
  #pie{
    
  }

  #act{
    width:100px;
  }


</style>




<!--cacha los mensajes de la sesion y los pone en div-->
@if(Session::has('message'))
<div class="alert alert-info" >{{session::get('message')}}</div>
@endif






<table class="table" id="tabindex">
  <thead class="thead-dark">
    <tr id="encab">
      <th scope="col">ID</th>
      <th scope="col" >NAME</th>
      <th scope="col" >TYPE</th>
      <th scope="col" >DESCRIPTION</th>
      <th scope="col" >ACTION</th>
      
      
    </tr>
  </thead>
  <tbody>
  
  @foreach($users as $user)

  <!--es codigo para la sintaxis eloquent-->
  {{-- @foreach($user->roles as $role) --}}

    <tr id="filas">

      <th scope="row">{{$user->id}}</th>
      <td >{{$user->usname}}</td>
      <td >{{$user->email}}</td>
      <td >{{$user->description}}</td>


      <!--es codigo para la sintaxis eloquent requiere un subforeach
      para recorrer lo que trae la parte de role-->
      
      {{-- <td >{{$role->name}}</td>
      <td >{{$role->description}}</td> --}}

      <!--el post llama al procedimiento edit del controlador, el cual llama a la view.
      a la par le manda como argumento el id de recipe-->
      <td id="but"><a id="edit" class="btn-sm btn-info" href="{{route('users.edit',$user->id)}}">Edit  </a>
      
      <!--se crearon las rutas automaticas de user porque se trata de otro modelo, asi
      se referencian las rutas mas facilmente

      el sistema de rutas de laravel esta optimizado para los objetos. todo funciono cuando
      hice el esquema para user->controlador->carpeta->resources. asi funcionaron correcta
      mente los botones del crud
      -->

      
      <form action="{{route('users.destroy',$user->id)}}" method="POST">
        @csrf
        @method('DELETE')
        <button id="elim" type="submit" onclick="return confirm('Desea aliminar el registro')" 
        class="btn-sm btn-danger">Delete</button></td>      
      </form>

      


      
    </tr>
    <!--es codigo para la sintaxis eloquent-->
    {{-- @endforeach --}}
    @endforeach

 </tbody>
</table>









</div>
@endsection