routes/web.php
<?php
use App\Type;
use App\Recipe;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/recipes/busca', function () {

    //pruebas para mostrar los datos relacionados
    //return Type::find(1)->recipe; 
    return Type::pluck("id","type");
});

//prueba para mostrar el id de un select al seleccionarlo
Route::get('/recipes/pruebas', function () {
    return view("/recipes/pruebas");
    
});

Route::get('/', function() 
{
    /*user=Auth::user();

    if($user->esAdmin())
    {
        echo 'Administrador';
    }
    else
    {
        echo 'Otro';
    };
*/ 
    //para que inicie con la vista de autenticacion
    return view("auth/login");
    
})->name('login');

//como en  las rutas automaticas toma la carpeta inicial recipes, en la ruta
//luego de public va recipes. y las diferentes views
Route::resource('recipes','RecipeController');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

//debe validar si es administrador para entrar al admin
Route::get('/admin','AdministradorController@Index');

//Route::get('/index_ru','UserController@index_ru');

Route::resource('users','UserController');
//Route::POST('/index_ru/destroy','UserController@destroy');




Route::get('/pdf', 'RecipeController@viewpdf');
   
   //$recipes= Recipe::all();
   //$pdf=PDF::LoadView('rep.r1',['recipes'=>$recipes]);
   //return $pdf->download('r1.pdf'); 
//});

/*
esta ruta se declaro para que se pueda invocar la funcion filePDF
duda: porque no pide ruta declarada para la otra funcion creada que
fue viewpdf. dice la ayuda que se requieren rutas para cualquier metodo
que se invoque desde formularios o enlaces
llamado desde un formulario con GET: <form action="{{action('RecipeController@filePDF')}}" method="GET">
*/
Route::GET('/filePDF', 'RecipeController@filePDF');
//Route::get('/filePDF', array('uses' => 'RecipeController@filePDF'));


/* <a href="{{url('recipes.indexdt')}}">Recipes DT</a> 
la duda es que no llama a la view por medio del controller, por lo 
tanto no le pasa los datos para llenar la tabla, y aun asi al abrir
sale la tabla llena
*/

/* llamar directo a la view para el datatable 
en primera instancia se aprecia que no deberia armarse data desde aqui
sino en el controlador

*/
Route::get('/indexdt', function(){
    $myres=Recipe::all();
    return view('recipes.indexdt')->with('myres',$myres);
});

Route::get('/indexcard', function(){
    $recipes=Recipe::orderby('id','desc')->take(3)->get();
    return view('recipes.indexcard')->with('recipes',$recipes);
});

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
		protected $fillable=['name','type_id','ingredients','procedure','route'];
	

    public function type()
		{
			return $this->belongsTo("App\Type","type_id","id");
		}

	// TERCER PASO: funcion que utiliza la barra de busqueda del index
	//prefijo scope
	//video: busquedas y filtros con laravel y eloquent (query scopes)
	//duilio palacion
	public function scopeName($query,$name){
		if(trim($name)!="")
		{
		//$query->where('name',$name);
		$query->where(\DB::raw("name"),"like","%$name%");
		//por ejemplo si se quisiera concatenar los campos, se utiliza sintaxis mysal
		//where(\DB::raw(CONCAT(name,secname),"like","%$ame%");
		
		
		}
	}
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Recipe;
use App\Type;
use Illuminate\Http\Request;
use Session;
use App\Http\Requests\RecipeStoreRequest;
use Reques;




class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req)
    {
        /** dd($req->get('name')); para comprobar que se esta mandandando un 
         * parametro name por POST
         * busca en los scopes de su clase el Name
        */

        $req->user()->authorizeRoles(['admin','user','guess']);

        // 2 PASO de la barra filtro: en el modelo recipe se creo la funcion name, asi que 
        //la utiliza para bucar
        $myres=Recipe::Name($req->get('name'))->orderby("id","desc")->paginate(10);
        
        return view('recipes.index')->with('myres',$myres);
        //return view("recipes.index",compact("myres"));
    }

    public function indexdt(Request $req)
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $req)
    {
        $req->user()->authorizeRoles(['admin','user']);
        //$mytype=Type::orderby("type","asc")->get();
        $mytype=Type::select("id","type")->get();
        //return view("recipes.create",compact("mytype"));
        return view("recipes.create")->with("mytype",$mytype);
        //mytype,$mytype son una referencia a la variable de arriba, el primero es
        //como un alias para la segunda, solo quita el $
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecipeStoreRequest $request)
    {
        //sintaxis para el selec de llave foranea
        //$datos=$request->all();
        //Recipe::create($datos);   
        
        //dd($request)
        //guardando control por control
        //$recipe=New Recipe;
        //$recipe->name=$request->name;
        //$recipe->ingredients=$request->ingredients;
        //$recipe->procedure=$request->procedure;
        //$recipe->type_id=$request->type_id;
        //$recipe->save();

        //guardando de un solo paso con request->all(), usado en tablas sin relacionar
        //Recipe::create($request->all());      
        

        //nuevo procedimiento que incluye el guardado de imagen
        $entrada=$request->all();

        if ($archivo=$request->file('file')){
            $nombre=$archivo->getClientOriginalName();
            $$archivo->move('public/images',$nombre);
            $entrada['route']=$nombre;
            
            
        }
        Recipe::create($entrada);

        Session::flash('message','Information saved');
        return redirect()->route('recipes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function show(Recipe $recipe)
    {
        //genera el pdf
        //$recipes=\App\Recipe::find($id);
        //$view=$view('recipes.show',compact('recipes'));
        //$pdf=\App::make('dompdf.wrapper');
        //$pdf->loadHTML($view);
        //return $pdf->stream('recipes');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Recipe $recipe, Request $req)
    {
        $req->user()->authorizeRoles(['admin','user']);
        //dd($recipe->route);
        
        return view("recipes.edit",compact('recipe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function update(RecipeStoreRequest $request, Recipe $recipe)
    {
        /*$request->validate([
            'recipe'=>'required',
            
        ]);*/

        $recipe->update($request->all());
        Session::flash('message','Information updated');
        return redirect()->route('recipes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function destroy(Recipe $recipe, Request $req)
    {
        $req->user()->authorizeRoles(['admin','user']);

        $recipe->delete();
        Session::flash('message','Information deleted');
        return redirect()->route('recipes.index');
    }


    public function viewpdf(){
        return view('recipes.pdf');
    }


    public function filePDF(Request $req)
    {
        //$recipes=Recipe::find($r->input('id')); //busca en reques 
        //todo lo que manda el formulario, el problema es que no implica 
        //seleccionar un id inicia vacio XXX
                
        $name=$req->get('name');//busca en la ruta ?id=2, pero se pone manual OK
        
        /* dd($req->get('name'));*/

        $recipes= Recipe::where('name',$name)->get(); //OK pero estatico
        $pdf=\PDF::LoadView('rep.r1',['recipes'=>$recipes]);
        //en el video no explica bien el porque del \PDF
        return $pdf->download('r1.pdf'); 
        echo "hi pdf";
    }
}

resources/views/recipes/create.blade.php
@extends('recipes.template')

@section('content')

<div class="container">

<h3>Create Recipe</h3>

<!--el post llama al procedimiento store del controlador-->
<form action="{{route('recipes.store')}}" method="POST" files=true>
@csrf

<!--<script>
function ShowSelected()
{
    var cod = document.getElementById("typelist").value;
    //alert(cod);
    $var=cod;
}
</script>
-->

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <strong>Recipe</strong>
            <input type="text" value="{{old('name')}}" name="name" class="form-control" 
            placeholder="recipe's name" style='text-transform:uppercase'>

            <strong>Ingredients</strong>
            <input type="text" value="{{old('ingredients')}}" name="ingredients" class="form-control" 
            placeholder="Ingredients" style='text-transform:uppercase'>

            <strong>Procedure</strong>
            <input type="text" value="{{old('procedure')}}" name="procedure" class="form-control" 
            placeholder="Procedure" style='text-transform:uppercase'>

             <!--cacha los errores del request-->
             @if($errors->has('name'))
                <strong class="text-danger">{{$errors->first('name')}}</strong>
                <br>   
            @endif

            <!--habilita el formulario para mandar archivos
        video 47 y 48 de pildoras informaticas
        puse post-->

            {!!Form::open(['url'=>'/recipes', 'method'=>'POST', 'files'=>'true'])!!}

            <div class="form-group">
            <strong>{!! Form::label("type_id","Type")!!}</strong>
            </div>
            
            {!!Form::select('type_id',$mytype->pluck('type','id')->all(),
            null,['placeholder'=>'--Seleccionar--','class'=>'form-control'])!!}
           
            <br>
                <!--abre la ventana seleccionar file-->
            {!!Form::file('file')!!}

           
            {!!Form::close()!!}

            <!--
            <strong>Type</strong>           
            <select id="typelist" name="type" class="form-control" onchange='ShowSelected();'>
            @foreach($mytype as $type)
                
                <option value='{{$type->id}}'>
                    {{$type->type}}
                </option>
            @endforeach
            </select>
            -->
            <!--
            <input type="text" value="" id="xxx" class="form-control" 
            placeholder="variable" >-->

        </div>
    </div>
    <div class="col-md-12 text-center" >
        <button type="submit" class="btn btn-primary">Save</button>
        
    </div>
</div>

</form>

</div>


@endsection

resources/views/recipes/edit.blade.php
@extends('recipes.template')

@section('content')

<div class="container">

<h3>Edit Recipe</h3>

<!--el post llama a la vista update y le pasa el id de recipe
mas abajo especifica que es con el metodo PUT-->
<form action="{{route('recipes.update',$recipe->id)}}" method="POST">
@csrf
@method('PUT')

<style>
#image{
    width:200px;
    height:220px
}
</style>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <strong>Name</strong>
            <input type="text" name="name" value="{{$recipe->name}}" 
            class="form-control" placeholder="recipe's name" style='text-transform:uppercase'>

            <strong>INGREDIENTS</strong>
            <input type="text" name="ingredients" value="{{$recipe->ingredients}}" 
            class="form-control" placeholder="ingredients" style='text-transform:uppercase'>

            <strong>PROCEDURE</strong>
            <input type="text" name="procedure" value="{{$recipe->procedure}}" 
            class="form-control" placeholder="procedure" style='text-transform:uppercase'>

            <!--no funciono con el codigo de pildoras-->
            <strong>IMAGE</strong>
            <img id='image' name="image" src="{{asset('images/'.$recipe->route)}}" class="form-control"/>
            
            <!--cacha error-->
            @if($errors->has('name'))
                <strong class="text-danger">{{$errors->first('name')}}</strong>
            @endif
        </div>
    </div>
    <!--
    <div class="col-md-12">
        <div class="form-group">
            <strong>Burn</strong>
            <input type="text" name="burn" value="{{$recipe->burn}}" class="form-control" placeholder="fecha de  nacimiento" >
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <strong>Notes</strong>
            <input type="text" name="notes" value="{{$recipe->notes}}" class="form-control" placeholder="notas" >
        </div>
    </div> -->
    <div class="col-md-12 text-center" >
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
    
</div>

</form>

</div>


@endsection

resources/views/recipes/index.blade.php
@extends('recipes.template_index')

@section('content')

<h2 class="text-center"></h2>

<div class='container'>


<!--se supone que manda a la vista create, AUNQUE SI EL CREATE DEL CONTROLADOR ESTA VACIO
NO MUESTRA NADA-->

<!--recordar que como esta administradas las rutas, es laravel quien pone 
'recipes + el nombre del metodo' aunque en la realidad no sea asi en la estructura
de carpetas-->

<a class="btn btn-info mb-2" href="{{route('recipes.create')}}">New recipe</a>

<style type="text/css">
  #tabindex{
    font-size:0.7em;
    
  }
 
  #tabindex #filas{
    padding:0.7em;
    
  }

  #tabindex #encab{
    padding:0.7em;
    
  }
 
  #elim, #edit{
    /*float:right;*/
    padding-top:0px;
    font-size:0.75em;
    
  }

  #elim{
    float:right;
    margin-top:-14px;

    width:38px;
    height:15px;
    font-size:0.73em;
  }

  #edit{
    width:50px;
    height:22px;

  }
  #pie{
    
  }

  #act{
    width:100px;
  }


</style>




<!--cacha los mensajes de la sesion y los pone en div-->
@if(Session::has('message'))
<div class="alert alert-info" >{{session::get('message')}}</div>
@endif

<table class="table" id="tabindex">
  <thead class="thead-dark">
    <tr id="encab">
      <th scope="col">ID</th>
      <th scope="col" >NAME</th>
      <!--<th scope="col">TYPE ID</th>-->
      <th scope="col" >INGREDIENTS</th>
      <th scope="col">PROCEDURE</th>
      <th scope="col" >TYPE</th>
      <th scope="col" id="act" >ACTIONS</th>
      
    </tr>
  </thead>
  <tbody>
  
  @foreach($myres as $recipe)
    <tr id="filas">

      <th scope="row">{{$recipe->id}}</th>
      <td >{{$recipe->name}}</td>
      <td >{{$recipe->ingredients}}</td>
      <td>{{$recipe->procedure}}</td>
      <!--
        AQUI NO POQUE NO ALCANZA LA TABLA, MEJOR EN EDIT QUE ES LA VISTA
        A DETALLE
      <td><img src='images/{{$recipe->route}}'></td>
      <td>{{$recipe->type_id}}</td>-->
      <td>{{$recipe->type->type}}</td>
      
      
     

      <!--el post llama al procedimiento edit del controlador, el cual llama a la view.
      a la par le manda como argumento el id de recipe-->
      <td id="but"><a id="edit" class="btn-sm btn-info" href="{{route('recipes.edit',$recipe->id)}}">Edit  </a>
      
      <!--otro form para otro post. el post llama al procedimiento destroy del 
      controlador-->
      <form action="{{route('recipes.destroy',$recipe->id)}}" method="POST">
        @csrf
       
        <button id="elim" type="submit" onclick="return confirm('Desea aliminar el registro')" 
        class="btn-sm btn-danger">Delete</button></td>      
      </form>

      


      
    </tr>
    @endforeach

 </tbody>
</table>
{{$myres->links()}}

</div>
@endsection

resources/views/recipes/indexcard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>


<style>
*{
  margin=0;
  padding=0;
  box-sizing:border-box;
}

.wrap{
  width:1100px;  
  margin:40px auto;

  display: flex;
  justify-content:center;  
}

.tarjeta-wrap{
 margin: 10px; 



-webkit-perspective:800;
perspective:800;

}

.tarjeta{
  background-color:orange;

  width:250px;
  height:300px;
  position:relative;
  
  transform-style:preserve-3d;
  transition: 0.7s ease;

  box-shadow: 2px 2px 10px green; 
}

.delante, .detras{
  height:100%;
  width:100%;
  
  position:absolute;

  top:0;
  left:0;

  backface-visibility:hidden;
  -webkit-backface-visibility:hidden;

  justify-content:center;
}

.detras{
  transform: rotateY(180deg);
}

.tarjeta-wrap:hover .tarjeta{
  transform: rotateY(180deg);
}




/*------------------------------------------------------------------
--------------------------------------------------------------------
*/
#name{
  
  font-size: 12px;
  text-align: center;

  
}

#descrip{
  
  font-size: 9px;
  text-align: center;

  
}

#image{
  width:250px;
  height:300;
}




</style>

<body>

<div class="wrap" >

  @foreach($recipes as $rec)
  <div class="tarjeta-wrap">
    <div class="tarjeta">
      <div class="delante">
        <img id="image" src="{{asset('images/'.$rec->route)}}"/><br>
        <strong id="name">{{$rec->name}}</strong> <br>
        
      </div>
      <div class="detras">
        <strong id="descrip">{{$rec->ingredients}}</strong> <br><br>
        <strong id="descrip">{{$rec->procedure}}</strong>
      </div>
    <!--del video : https://www.youtube.com/watch?v=5mrkxGPzyK0
    tarjeta 3d con efecto flip-->  
    </div>
    
  </div>

  @endforeach
</div>

</body>
</html>

resources/views/recipes/indexdt.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>


<!--hojas de estilos de datatable.net-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">


<body>
  


<div id="container">

<!--segun el video de rimorsoft online tip 3 y 4, data tables y ajax en laravel
data tables
-->
<table id="recipesdt" class="table">
<thead>
  <tr>
    <th>ID</th>
    <th>NAME</th>
    <th>INGREDIENTS</th>
    <th>PROCEDURE</th>
    
    
  </tr>
</thead>
<tbody>
@foreach($myres as $mr)
  <tr>
    <td>{{$mr->id}}</td>
    <td>{{$mr->name}}</td>
    <td>{{$mr->ingredients}}</td>
    <td>{{$mr->procedure}}</td>
    
  </tr>
@endforeach
</tbody>

</table>




<!--los scripts de datatable.net-->
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
$('#recipesdt').DataTable();
});
</script>

</div>



</body>
</html>

resources/views/recipes/pdf.blade.php
@extends('recipes.template')

@section('content')

<h3>Reports</h3>

 
<!--
<form method="POST">
<a class="nav-link" href="{{action('RecipeController@filePDF')}}">Report</a>
</form>
-->

<form action="{{action('RecipeController@filePDF')}}" method="GET">

<strong>Name</strong>
<input type="text" value="{{old('name')}}" name="name" class="form-control" 
     placeholder="recipe's name" style='text-transform:uppercase'>
    <button type="submit"  class="btn-sm btn-info">Ver PDF</button>
</form>

@endsection

resources/views/recipes/pruebas.blade.php
<script>
function ShowSelected()
{
    var cod = document.getElementById("typelist").value;
    alert(cod);
}
</script>


<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            

            <strong>Country</strong>
           
            <select id="typelist" name="type" class="" onchange="ShowSelected();">
                <option value="1">MEXICO</option> 
                <option value="2">EEUU</option> 
                <option value="3">CANADA</option>         
            </select>
            <!--
            <input type="text" value="" id="xxx" class="form-control" 
            placeholder="variable" >-->

            
        </div>
    </div>
    <div class="col-md-12 text-center" >
        <button type="submit" class="btn btn-primary" >Save</button>
        
    </div>
</div>

resources/views/recipes/template.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>My Recipes!</title>
  </head>
  <body>
    
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{{url('/')}}">My Recipes !</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <!--<a class="nav-link" href="recipes/verpdf">Reports</a>-->
        <a class="nav-link" href="{{action('RecipeController@viewpdf')}}">Report</a>
      </li>
      <li class="nav-item">
        <!--<a class="nav-link" href="recipes/verpdf">Reports</a>-->
        <a class="nav-link" href="{{route('users.index')}}">Maintenance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>


    <!-- PRIMER PASO se pusieron etiquetas dinamicas para la busqueda de recetas
    video : busquedas y filtros con laravel y eloquent(query scopes); dulio palacios-->

    {{-- se quito la busqueda para las vistas que no tienen lista
      {!! Form::open(['route'=>'recipes.index','method'=>'GET','class'=>'form-inline my-2 my-lg-0',
    'rolle'=>'search'])!!}
      {!! Form::text('name',null,['class'=>'form-control','place-holder'=>'Buscar nombre de receta'])  !!}   
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar nombre de receta</button>
    {!!Form::close()!!} --}}
  </div>
</nav>

    
    @yield('content')


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/recipes/template_index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>My Recipes!</title>
  </head>
  <body>
    
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{{url('/')}}">My Recipes !</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <!--<a class="nav-link" href="recipes/verpdf">Reports</a>-->
        <a class="nav-link" href="{{action('RecipeController@viewpdf')}}">Report</a>
      </li>
      <li class="nav-item">
        <!--<a class="nav-link" href="recipes/verpdf">Reports</a>-->
        <a class="nav-link" href="{{route('users.index')}}">Maintenance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>


    <!-- PRIMER PASO se pusieron etiquetas dinamicas para la busqueda de recetas
    video : busquedas y filtros con laravel y eloquent(query scopes); dulio palacios-->

    {!! Form::open(['route'=>'recipes.index','method'=>'GET','class'=>'form-inline my-2 my-lg-0',
    'rolle'=>'search'])!!}
      {!! Form::text('name',null,['class'=>'form-control','place-holder'=>'Buscar nombre de receta'])  !!}   
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar nombre de receta</button>
    {!!Form::close()!!}
  </div>
</nav>

    
    @yield('content')


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>